### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by yuvadm**
Just passed the existing code through 2to3. Sanity test assistance would be helpful!

### CODE REVIEW

**Comment by flokli** [comment]
@yuvadm, @lukasklein: I found three more typos where you wrote `force_test` instead of `force_text`. Annotated inside 5f3f19ca76c240a615eddce9df738ce3ee7fd12f.

Probably you should squash the commits together, to get a better about the differences.

**Comment by fdintino** [comment]
Yes I noticed those typos as well.

I'm afraid I'll need to rework this quite a bit before I can merge it. Personally, I don't really understand the popularity of 2to3 since it isn't backwards compatible. That's a non-starter for me. It seems to me much more appropriate to use `six` to maintain cross-compatibility between python 2 and 3. For instance, the `class Foo(object, metaclass=X)` syntax only works in python 3, whereas the `@six.add_metaclass(X)` class decorator is cross-compatible. For an example of the sort of thing I would be looking for, here's a python 3 compatibility commit for another (much more complicated) project: [https://github.com/theatlantic/django-cropduster/commit/217eebaaab566ca7439a4104ccb9fc124db07daf]

We at The Atlantic still use python 2 in production, though obviously it's best if our open source libraries run on 2 and 3. Unfortunately without something like tox and travis we're liable to introduce regressions in the python 3 with our development, so I would also like to get some unit tests in the project. That's not a blocker for python 3 support, but definitely something I'm looking to add.

**Comment by flokli** [comment]
@fdintino Thanks for your reply! I currently use Python 3, so I'm fine with a python3-only version ;-)

However, being compatible to both versions does make sense :-)

I fixed the typos and pushed a squashed commit to https://github.com/flokli/django-select2-forms/tree/py3 , feel free to use it if you want :+1:

**Comment by yuvadm** [comment]
@flokli thanks for taking the initiative and doing this :smile_cat:

**Comment by fdintino** [comment]
Closing this pull request as it breaks python 2 compatibility

**Pull request closed without merging**
